version: "2.0"

paths:

  raw_root: "../../../raw"

  csv_root: "../../../abox/slovpedia/era-sk/zsr-opendata/2-0/csv"

  rdf_root: "../../../abox/slovpedia/era-sk/zsr-opendata/2-0/rdf"


publisher:

  name: "Ministerstvo dopravy Slovenskej republiky"

  uri: "https://data.gov.sk/id/legal-subject/30416094"


dataset:

  dataset_base: "https://slovpedia.eu/dataset/{dataset_uid}"

  distribution_base: "https://slovpedia.eu/dataset/{dataset_uid}/distribution/{distribution_uid}"


uri:

  operational_point:
    pattern: "https://slovpedia.eu/id/era/operational-point/{id}"

  network_section:
    pattern: "https://slovpedia.eu/id/era/network-section/{id}"

  section_of_line:
    pattern: "https://slovpedia.eu/id/era/section-of-line/{id}"

  running_track:
    pattern: "https://slovpedia.eu/id/era/running-track/{section_of_line_id}/{track_id}"

  platform_edge:
    pattern: "https://slovpedia.eu/id/era/platform-edge/{id}"

  tunnel:
    pattern: "https://slovpedia.eu/id/era/tunnel/{id}"

  etcs_track_deployment:
    pattern: "https://slovpedia.eu/id/era/etcs-track-deployment/{id}"


datasets:

  #
  # InfoMapa ŽSR
  #

  rinf_operational_points:

    source_file: "{raw_root}/zsr-infomapa/doprbody_idvrstva_3.json"

    csv: "{csv_root}/rinf/rinf_operational_points.csv"

    rdf: "{rdf_root}/rinf/rinf_operational_points.ttl"


  rinf_network_sections:

    source_file: "{raw_root}/zsr-infomapa/dopruseky_idvrstva_3.json"

    csv: "{csv_root}/rinf/rinf_network_sections.csv"

    rdf: "{rdf_root}/rinf/rinf_network_sections.ttl"


  #
  # Data Slovensko
  #

  rinf_sections_of_line:

    source_csv: "{raw_root}/data-slovensko-sk/Zoznam železničných tratí v SR za rok 2025.csv"

    csv: "{csv_root}/rinf/rinf_sections_of_line.csv"

    rdf: "{rdf_root}/rinf/rinf_sections_of_line.ttl"


  #
  # Budúce datasety
  #

  rinf_running_tracks:

    csv: "{csv_root}/rinf/rinf_running_tracks.csv"

    rdf: "{rdf_root}/rinf/rinf_running_tracks.ttl"


  rinf_platform_edges:

    csv: "{csv_root}/rinf/rinf_platform_edges.csv"

    rdf: "{rdf_root}/rinf/rinf_platform_edges.ttl"


  rinf_tunnels:

    csv: "{csv_root}/rinf/rinf_tunnels.csv"

    rdf: "{rdf_root}/rinf/rinf_tunnels.ttl"


  rinf_etcs_running:

    csv: "{csv_root}/rinf/rinf_etcs_running.csv"

    rdf: "{rdf_root}/rinf/rinf_etcs_running.ttl"


  rinf_etcs_track_deployments_operational:

    csv: "{csv_root}/rinf/rinf_etcs_track_deployments_operational.csv"

    rdf: "{rdf_root}/rinf/rinf_etcs_track_deployments_operational.ttl"


  rinf_etcs_track_deployments_planned:

    csv: "{csv_root}/rinf/rinf_etcs_track_deployments_planned.csv"

    rdf: "{rdf_root}/rinf/rinf_etcs_track_deployments_planned.ttl"


  rinf_etcs_track_deployments_under_construction:

    csv: "{csv_root}/rinf/rinf_etcs_track_deployments_under_construction.csv"

    rdf: "{rdf_root}/rinf/rinf_etcs_track_deployments_under_construction.ttl"


  rinf_operational_point_net_references:

    csv: "{csv_root}/rinf/rinf_operational_point_net_references.csv"

    rdf: "{rdf_root}/rinf/rinf_operational_point_net_references.ttl"
